apiVersion: v1
kind: Service
metadata:
  name: capstone-production
  labels:
    run: capstone
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: capstone-green
  type: LoadBalancer
